package org.im.dc.client.ui.xmlstructure.tlum;

public class XmlEditOneParadigmPanel extends javax.swing.JPanel {

    /**
     * Creates new form XmlEditOneParadigmPanel
     */
    public XmlEditOneParadigmPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        cbPara = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        rbOne = new javax.swing.JRadioButton();
        rbMany = new javax.swing.JRadioButton();
        cbOneNieskl = new javax.swing.JCheckBox();
        cbManyNieskl = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtResult = new javax.swing.JEditorPane();

        setMinimumSize(new java.awt.Dimension(200, 100));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(200, 300));
        setLayout(new java.awt.GridBagLayout());

        cbPara.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(cbPara, gridBagConstraints);

        jLabel1.setText("Асноўны лік:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        add(jLabel1, gridBagConstraints);

        buttonGroup1.add(rbOne);
        rbOne.setSelected(true);
        rbOne.setText("адзіночны");
        rbOne.setOpaque(false);
        rbOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        add(rbOne, gridBagConstraints);

        buttonGroup1.add(rbMany);
        rbMany.setText("множны");
        rbMany.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        add(rbMany, gridBagConstraints);

        cbOneNieskl.setText("нескл.");
        cbOneNieskl.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        add(cbOneNieskl, gridBagConstraints);

        cbManyNieskl.setText("нескл.");
        cbManyNieskl.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        add(cbManyNieskl, gridBagConstraints);

        jPanel1.setOpaque(false);

        jCheckBox3.setText("разм.");
        jCheckBox3.setOpaque(false);
        jPanel1.add(jCheckBox3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(jPanel1, gridBagConstraints);

        jScrollPane2.setOpaque(false);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Склон", "м.", "ж.", "н.", "мн."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setOpaque(false);
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(jScrollPane2, gridBagConstraints);

        txtResult.setEditable(false);
        txtResult.setContentType("text/html"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(txtResult, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void rbOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JCheckBox cbManyNieskl;
    public javax.swing.JCheckBox cbOneNieskl;
    public javax.swing.JComboBox<String> cbPara;
    public javax.swing.JCheckBox jCheckBox3;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JRadioButton rbMany;
    public javax.swing.JRadioButton rbOne;
    public javax.swing.JTable table;
    public javax.swing.JEditorPane txtResult;
    // End of variables declaration//GEN-END:variables
}
