/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.im.dc.client.ui.utils;

/**
 *
 * @author alex
 */
public class DiffPanel extends javax.swing.JPanel {

    /**
     * Creates new form DiffPanel
     */
    public DiffPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        split = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        text1 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        text2 = new javax.swing.JEditorPane();
        scrollHorizontal = new javax.swing.JScrollBar();
        scrollVertical = new javax.swing.JScrollBar();

        setLayout(new java.awt.BorderLayout());

        split.setResizeWeight(0.5);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBar(scrollHorizontal);
        jScrollPane1.setVerticalScrollBar(scrollVertical);

        text1.setEditable(false);
        jScrollPane1.setViewportView(text1);

        split.setLeftComponent(jScrollPane1);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setHorizontalScrollBar(scrollHorizontal);
        jScrollPane2.setVerticalScrollBar(scrollVertical);

        text2.setEditable(false);
        jScrollPane2.setViewportView(text2);

        split.setRightComponent(jScrollPane2);

        add(split, java.awt.BorderLayout.CENTER);

        scrollHorizontal.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        add(scrollHorizontal, java.awt.BorderLayout.SOUTH);

        scrollVertical.setBlockIncrement(100);
        scrollVertical.setUnitIncrement(30);
        add(scrollVertical, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollBar scrollHorizontal;
    public javax.swing.JScrollBar scrollVertical;
    public javax.swing.JSplitPane split;
    public javax.swing.JEditorPane text1;
    public javax.swing.JEditorPane text2;
    // End of variables declaration//GEN-END:variables
}
