package org.im.dc.client.ui;

public class ArticleEditDialog extends javax.swing.JDialog {

    /**
     * Creates new form ArticleEditDialog
     */
    public ArticleEditDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtState = new javax.swing.JTextField();
        txtUsers = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        lblHasProposedChanges = new javax.swing.JLabel();
        lblWatched = new javax.swing.JLabel();
        lblPreview = new javax.swing.JLabel();
        lblValidationError = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnChangeState = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnAddIssue = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        panelLinkedFrom = new javax.swing.JPanel();
        panelLinkedExternal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/im/dc/client/ui/Bundle"); // NOI18N
        setTitle(bundle.getString("ArticleEditDialog.title")); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.GridBagLayout());

        txtState.setEditable(false);
        txtState.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtState.setToolTipText(bundle.getString("ArticleEditDialog.txtState.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(txtState, gridBagConstraints);

        txtUsers.setEditable(false);
        txtUsers.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsers.setToolTipText(bundle.getString("ArticleEditDialog.txtUsers.toolTipText")); // NOI18N
        txtUsers.setMinimumSize(new java.awt.Dimension(60, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel6.add(txtUsers, gridBagConstraints);

        jPanel5.add(jPanel6, java.awt.BorderLayout.WEST);

        lblHasProposedChanges.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/im/dc/client/ui/images/proposed-off.png"))); // NOI18N
        lblHasProposedChanges.setToolTipText(bundle.getString("ArticleEditDialog.lblHasProposedChanges.toolTipText")); // NOI18N
        jPanel7.add(lblHasProposedChanges);

        lblWatched.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/im/dc/client/ui/images/watch-off.png"))); // NOI18N
        lblWatched.setToolTipText(bundle.getString("ArticleEditDialog.lblWatched.toolTipText")); // NOI18N
        jPanel7.add(lblWatched);

        lblPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/im/dc/client/ui/images/show-text.png"))); // NOI18N
        lblPreview.setToolTipText(bundle.getString("ArticleEditDialog.lblPreview.toolTipText")); // NOI18N
        jPanel7.add(lblPreview);

        jPanel5.add(jPanel7, java.awt.BorderLayout.EAST);

        lblValidationError.setForeground(new java.awt.Color(255, 0, 0));
        lblValidationError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(lblValidationError, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        btnChangeState.setText(bundle.getString("ArticleEditDialog.btnChangeState.text")); // NOI18N
        jPanel4.add(btnChangeState);

        jPanel2.add(jPanel4, java.awt.BorderLayout.WEST);

        btnAddIssue.setText(bundle.getString("ArticleEditDialog.btnAddIssue.text")); // NOI18N
        jPanel3.add(btnAddIssue);

        btnSave.setText(bundle.getString("ArticleEditDialog.btnSave.text")); // NOI18N
        jPanel3.add(btnSave);

        jPanel2.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel9.setLayout(new java.awt.BorderLayout());

        panelLinkedFrom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel9.add(panelLinkedFrom, java.awt.BorderLayout.WEST);

        panelLinkedExternal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        jPanel9.add(panelLinkedExternal, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel9, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArticleEditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArticleEditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArticleEditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArticleEditDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArticleEditDialog dialog = new ArticleEditDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddIssue;
    public javax.swing.JButton btnChangeState;
    public javax.swing.JButton btnSave;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel9;
    public javax.swing.JLabel lblHasProposedChanges;
    public javax.swing.JLabel lblPreview;
    public javax.swing.JLabel lblValidationError;
    public javax.swing.JLabel lblWatched;
    public javax.swing.JPanel panelLinkedExternal;
    public javax.swing.JPanel panelLinkedFrom;
    public javax.swing.JTextField txtState;
    public javax.swing.JTextField txtUsers;
    // End of variables declaration//GEN-END:variables
}
