package org.im.dc.client.ui;

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miUsers = new javax.swing.JMenuItem();
        miAddArticle = new javax.swing.JMenuItem();
        miPreview = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miSettings = new javax.swing.JMenuItem();
        miStat = new javax.swing.JMenuItem();
        miAddWords = new javax.swing.JMenuItem();
        miValidateFull = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/im/dc/client/ui/Bundle"); // NOI18N
        setTitle(bundle.getString("MainFrame.title")); // NOI18N

        jMenu1.setText(bundle.getString("MainFrame.jMenu1.text")); // NOI18N

        miUsers.setText(bundle.getString("MainFrame.miUsers.text")); // NOI18N
        jMenu1.add(miUsers);

        miAddArticle.setText(bundle.getString("MainFrame.miAddArticle.text")); // NOI18N
        jMenu1.add(miAddArticle);

        miPreview.setText(bundle.getString("MainFrame.miPreview.text")); // NOI18N
        jMenu1.add(miPreview);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(bundle.getString("MainFrame.jMenu2.text")); // NOI18N

        miSettings.setText(bundle.getString("MainFrame.miSettings.text")); // NOI18N
        jMenu2.add(miSettings);

        miStat.setText(bundle.getString("MainFrame.miStat.text")); // NOI18N
        jMenu2.add(miStat);

        miAddWords.setText(bundle.getString("MainFrame.miAddWords.text")); // NOI18N
        jMenu2.add(miAddWords);

        miValidateFull.setText(bundle.getString("MainFrame.miValidateFull.text")); // NOI18N
        jMenu2.add(miValidateFull);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem miAddArticle;
    public javax.swing.JMenuItem miAddWords;
    public javax.swing.JMenuItem miPreview;
    public javax.swing.JMenuItem miSettings;
    public javax.swing.JMenuItem miStat;
    public javax.swing.JMenuItem miUsers;
    public javax.swing.JMenuItem miValidateFull;
    // End of variables declaration//GEN-END:variables
}
