/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.im.dc.client.ui;

/**
 *
 * @author alex
 */
public class MainFramePanelNews extends javax.swing.JPanel {

    /**
     * Creates new form MainFramePanelNews
     */
    public MainFramePanelNews() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tableNews = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tableNews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/im/dc/client/ui/Bundle"); // NOI18N
        tableNews.setToolTipText(bundle.getString("MainFrame.tableNews.toolTipText")); // NOI18N
        tableNews.setName("news"); // NOI18N
        tableNews.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane3.setViewportView(tableNews);

        add(jScrollPane3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable tableNews;
    // End of variables declaration//GEN-END:variables
}
